language: cpp
env:
  global:
      - secure: "KXrNrSs66/J5fb8pRYTUhIjEiXizlZ7p0xVROPla+GWfwyLJIAiswbwYOBpR1kSTn51E+j6j14UWL36GC31TK5WXRJoWoyVXi1RH+zZfvESAwqI6OmhzTWQd84fyXJ+vx5Yg0qEhPGH0HFGaNrpAvsBtr8lmsoLgocEaMikqxQ8="

matrix:
  include:
    - os: osx
      osx_image: osx10.11
      env: OSX=10.11
      compiler: clang
    - os: osx
      osx_image: xcode7
      env: OSX=10.10
      compiler: clang
    - os: osx
      osx_image: beta-xcode6.2
      env: OSX=10.9
      compiler: clang
    - os: linux
      addons:
        apt:
          packages:
          - gfortran
  allow_failures:
    - os: osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$OSX" == "10.10" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$OSX" == "10.10" ]]; then brew install gcc; fi
  - git clone https://github.com/coin-or-tools/BuildTools
  - bash BuildTools/get.dependencies.sh fetch > /dev/null

script:
  - bash BuildTools/get.dependencies.sh build --quiet
  - cd /home/travis/build/tkralphs/MibS/build/bin && \
    LD_LIBRARY_PATH=/home/travis/tkralphs/MibS/build/lib ./mibs \ 
    -Alps_instance ../../data/interdiction/MCDM/NO_CORR/10_ITEMS_1000/K5010W03.KNP.mps \
    -MibS_auxiliaryInfoFile ../../data/interdiction/MCDM/NO_CORR/10_ITEMS_1000/K5010W03.KNP.txt

after_script:
  - if [ $TRAVIS_BRANCH = "library" ]; then export VERSION=trunk; else export VERSION=`echo $TRAVIS_BRANCH | cut -d "/" -f 2`; fi
  - export PROJECT=`echo $TRAVIS_REPO_SLUG | cut -d "/" -f 2`
  - export TGZ_FILE=$PROJECT-$VERSION-$PLATFORM.tgz
  - echo $TGZ_FILE
  - tar -czvf $TGZ_FILE build/lib/* build/bin/* build/include/* build/share/* build/README.md build/INSTALL build/LICENSE build/SYMPHONY/AUTHORS
  - curl -T $TGZ_FILE -utkralphs:$BINTRAY_API -H "X-Bintray-Publish:1" -H "X-Bintray-Override:1" https://api.bintray.com/content/coin-or/download/$PROJECT/$VERSION/$TGZ_FILE